import { useCallback, useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { Award, BriefcaseBusiness, CalendarClock, CheckCircle2, ChevronRight, CircleUserRound, Crown, FileCheck2, Filter, Gem, MapPin, RefreshCw, Search, ShieldCheck, Sparkles, Target, UserCheck, Users, WalletCards, XCircle } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { SEO } from "@/components/SEO";
import { toast } from "sonner";
import { listAllApplications, listRecruiters, type Application, type Recruiter } from "@/lib/recruitment";
import { supabase } from "@/integrations/supabase/client";

const CAMPAIGN = "CY-NWANKWO-FARM-OPERATIONS";
type Flow = "all"|"applicants"|"screening"|"verification"|"shortlist"|"interview"|"selected"|"onboarding"|"placed";
const FLOW: {key:Flow;label:string;icon:any}[] = [
  {key:"all",label:"Command",icon:Crown},{key:"applicants",label:"Applicants",icon:Users},{key:"screening",label:"Screening",icon:Search},
  {key:"verification",label:"Verification",icon:ShieldCheck},{key:"shortlist",label:"Shortlist",icon:UserCheck},{key:"interview",label:"CY Interview",icon:CalendarClock},
  {key:"selected",label:"Selected",icon:Award},{key:"onboarding",label:"Onboarding",icon:FileCheck2},{key:"placed",label:"Placed",icon:Target},
];
type V = {application_id:string;verification_type:string;provider:string;status:string;match_result:string|null};
const stageLabel:Record<string,string>={new:"Applicant",contacted:"Screening",qualified:"Shortlisted",interview_scheduled:"CY Interview",interview_completed:"Interview Complete",accepted:"Selected",enrolled:"Onboarding",certified:"Ready",deployed:"Placed",archived:"Archived"};
const verified=(r:Application,v:V[])=>v.some(x=>x.application_id===r.id&&x.status==="verified");
function flow(r:Application,v:V[]):Flow{
 if(r.stage==="deployed")return"placed"; if(["enrolled","certified"].includes(r.stage))return"onboarding"; if(r.stage==="accepted")return"selected";
 if(["interview_scheduled","interview_completed"].includes(r.stage))return"interview"; if(r.stage==="qualified")return"shortlist";
 if(r.stage==="contacted")return verified(r,v)?"verification":"screening"; return"applicants";
}
function readiness(r:Application,v:V[]){return Math.round(([r.full_name, r.phone||r.email, r.location, r.education, r.prior_experience, verified(r,v)].filter(Boolean).length/6)*100)}
function tone(s:string){const x=s.toLowerCase();return x.includes("verified")||x.includes("selected")||x.includes("placed")||x.includes("ready")?"border-emerald-300/25 bg-emerald-300/[.08] text-emerald-200":"border-amber-300/20 bg-amber-300/[.06] text-amber-200"}

export default function CYRecruitmentMatrix(){
 const [rows,setRows]=useState<Application[]>([]),[recs,setRecs]=useState<Recruiter[]>([]),[vers,setVers]=useState<V[]>([]),[selected,setSelected]=useState<Application|null>(null),[active,setActive]=useState<Flow>("all"),[search,setSearch]=useState(""),[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{setLoading(true);try{const [a,r]=await Promise.all([listAllApplications({campaign:CAMPAIGN}),listRecruiters()]);setRows(a);setRecs(r);if(a.length){const {data,error}=await supabase.from("candidate_verifications").select("application_id,verification_type,provider,status,match_result").in("application_id",a.map(x=>x.id)).order("created_at",{ascending:false});if(!error)setVers((data??[]) as V[])}else setVers([])}catch(e){toast.error(e instanceof Error?e.message:"Could not load CY recruitment data")}finally{setLoading(false)}},[]);
 useEffect(()=>{load()},[load]);
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return rows.filter(r=>(active==="all"||flow(r,vers)===active)&&(!q||[r.full_name,r.email,r.phone,r.location,r.program,r.reference_number,r.education].filter(Boolean).some(x=>String(x).toLowerCase().includes(q))))},[rows,vers,active,search]);
 const count=(f:Flow)=>f==="all"?rows.length:rows.filter(r=>flow(r,vers)===f).length;
 const recruiter=(id:string|null)=>(id&&recs.find(r=>r.user_id===id)?.display_name)||"Unassigned";
 return <div className="mx-bg min-h-screen text-white"><SEO title="CY Farm Luxury Recruitment Command Center" path="/admin/cy-recruitment" description="Premium CY farm recruitment command center" noindex/>
  <header className="sticky top-0 z-40 border-b border-amber-200/10 bg-[#050505]/85 backdrop-blur-2xl"><div className="mx-auto flex max-w-[1700px] items-center justify-between gap-4 px-4 py-3 md:px-8"><div className="flex items-center gap-3"><div className="lux-icon"><Gem/></div><div><div className="eyebrow">ResoFlex™ Executive Workforce Suite</div><div className="font-display text-lg">CY Farms · Recruitment Command</div></div></div><div className="flex gap-2"><Button variant="glass" size="sm" onClick={load}><RefreshCw className={loading?"mr-2 h-4 w-4 animate-spin":"mr-2 h-4 w-4"}/>Refresh</Button><Button variant="glass" size="sm" asChild><Link to="/admin/farm-command-center">Farm Command</Link></Button></div></div></header>
  <main className="relative mx-auto max-w-[1700px] px-4 py-7 md:px-8">
   <section className="lux-hero"><div className="relative grid gap-8 lg:grid-cols-[1.25fr_.75fr] lg:items-end"><div><div className="flex flex-wrap gap-2"><Badge className="border border-amber-300/25 bg-amber-300/10 text-amber-200">LIVE PRODUCTION DATA</Badge><Badge variant="outline" className="border-white/10 text-white/45">{CAMPAIGN}</Badge></div><div className="mt-6 eyebrow flex items-center gap-2"><Sparkles className="h-4 w-4"/> CEO / Client Review Surface</div><h1 className="mt-2 max-w-4xl font-display text-4xl leading-none md:text-6xl">A premium command room for <span className="text-gradient-gold">every candidate decision.</span></h1><p className="mt-5 max-w-3xl text-sm leading-7 text-white/50 md:text-base">Applicant → screening → verification → shortlist → CY interview → selection → onboarding → placement. Every stage is navigable, evidence-led and presented as a decision-ready profile.</p></div><div className="grid grid-cols-2 gap-3">{[[Users,"Applicants",rows.length],[ShieldCheck,"Verified",vers.filter(x=>x.status==="verified").length],[CalendarClock,"Interviews",count("interview")],[Award,"Selected+",rows.filter(r=>["accepted","enrolled","certified","deployed"].includes(r.stage)).length]].map(([I,l,n]:any)=><div className="lux-metric" key={l}><I className="h-4 w-4 text-amber-200/70"/><div className="mt-4 font-tactical text-3xl">{n}</div><div className="eyebrow mt-1">{l}</div></div>)}</div></div></section>
   <nav className="mt-5 overflow-x-auto pb-1"><div className="flex min-w-max gap-2">{FLOW.map(({key,label,icon:I})=><button key={key} onClick={()=>setActive(key)} className={`flow-tab ${active===key?"flow-active":""}`}><div className="flex items-center justify-between gap-5"><I className="h-4 w-4"/><span className="font-tactical text-lg">{count(key)}</span></div><div className="mt-2 text-xs">{label}</div></button>)}</div></nav>
   <section className="mt-7"><div className="mb-5 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="eyebrow">{active==="all"?"Executive overview":FLOW.find(x=>x.key===active)?.label}</div><h2 className="font-display text-3xl">{active==="all"?"Candidate decision gallery":FLOW.find(x=>x.key===active)?.label}</h2><p className="mt-2 text-sm text-white/40">{active==="all"?"Open any profile for the complete evidence and next-gate view.":"Each record is presented as a premium candidate dossier rather than a generic document row."}</p></div><div className="flex items-center gap-2"><Filter className="h-4 w-4 text-white/25"/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search candidate, role, location…" className="w-full border-white/10 bg-white/[.035] md:w-80"/></div></div>
   {loading?<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{[1,2,3,4,5,6].map(i=><Skeleton key={i} className="h-80 rounded-[1.5rem] bg-white/[.035]"/>)}</div>:filtered.length?<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map(r=><CandidateCard key={r.id} r={r} v={vers} recruiter={recruiter(r.assigned_recruiter)} onOpen={()=>setSelected(r)}/>)}</div>:<Empty active={active}/>}</section>
   <footer className="mt-12 border-t border-white/10 pt-5 text-[9px] uppercase tracking-[.25em] text-white/25 flex justify-between"><span>ResoFlex™ powered by Resonance Fitness</span><span>Recorded facts only · explicit client decision gates</span></footer>
  </main>
  <Detail row={selected} v={vers} recruiter={selected?recruiter(selected.assigned_recruiter):"Unassigned"} close={()=>setSelected(null)}/>
 </div>
}

function CandidateCard({r,v,recruiter,onOpen}:{r:Application;v:V[];recruiter:string;onOpen:()=>void}){
 const f=flow(r,v),ok=verified(r,v),pct=readiness(r,v),vc=v.filter(x=>x.application_id===r.id).length;
 return <button onClick={onOpen} className="candidate-card group"><div className="candidate-top"><div className="flex min-w-0 items-center gap-3"><div className="avatar-lux"><CircleUserRound/></div><div className="min-w-0"><div className="truncate font-display text-lg">{r.full_name||"Name not recorded"}</div><div className="eyebrow mt-1 truncate">{r.reference_number||r.id.slice(0,8)}</div></div></div><Badge className={`shrink-0 ${tone(stageLabel[r.stage]||r.stage)}`}>{stageLabel[r.stage]||r.stage}</Badge></div>
 <div className="role-lux"><div className="eyebrow">Role / assignment</div><div className="mt-1 text-sm font-medium">{r.program||"Role not recorded"}</div><div className="mt-1 flex items-center gap-1 text-[11px] text-white/35"><MapPin className="h-3 w-3"/>{r.location||"Location not recorded"}</div></div>
 <div className="grid grid-cols-2 gap-2 mt-4"><Fact label="Education" value={r.education}/><Fact label="Experience" value={r.prior_experience}/><Fact label="Evidence" value={ok?vc+" verification record"+(vc===1?"":"s"):"Not verified"}/><Fact label="Recruiter" value={recruiter}/></div>
 <div className="mt-5"><div className="flex justify-between eyebrow"><span>Profile readiness</span><span className="text-amber-200/80">{pct}%</span></div><div className="mt-2 h-1.5 rounded-full bg-white/7 overflow-hidden"><div className="h-full bg-gradient-to-r from-amber-400 to-yellow-100" style={{width:pct+"%"}}/></div></div>
 <div className="mt-5 border-t border-white/8 pt-4 flex justify-between items-center"><span className="eyebrow flex items-center gap-2"><i className="h-1.5 w-1.5 rounded-full bg-amber-300"/>{f}</span><span className="eyebrow text-amber-200/70 group-hover:text-white">Open dossier <ChevronRight className="inline h-3.5 w-3.5"/></span></div></button>
}
function Fact({label,value}:{label:string;value:string|null}){return <div className="fact-lux"><div className="eyebrow">{label}</div><div className="mt-1 line-clamp-2 text-[11px] leading-5 text-white/55">{value||"Not recorded"}</div></div>}
function Empty({active}:{active:Flow}){return <div className="lux-empty"><Sparkles className="mx-auto h-7 w-7 text-amber-200/25"/><div className="mt-3 font-display text-lg text-white/55">No records in {active.replace("_"," ")}.</div><div className="mt-1 text-xs text-white/25">Empty production states are preserved; no candidate data is invented.</div></div>}

function Detail({row,v,recruiter,close}:{row:Application|null;v:V[];recruiter:string;close:()=>void}){
 if(!row)return null; const ok=verified(row,v),pct=readiness(row,v),f=flow(row,v),records=v.filter(x=>x.application_id===row.id);
 const checks=[["Identity/contact",Boolean(row.full_name&&(row.phone||row.email))],["Location",Boolean(row.location)],["Education",Boolean(row.education)],["Experience",Boolean(row.prior_experience)],["Verification",ok]];
 return <Dialog open={!!row} onOpenChange={x=>!x&&close()}><DialogContent className="max-h-[94vh] max-w-6xl overflow-y-auto border-amber-200/15 bg-[#080808] p-0 text-white shadow-[0_40px_140px_rgba(0,0,0,.75)]"><div className="detail-hero"><DialogHeader><div className="flex items-start justify-between gap-5 pr-5"><div className="flex gap-4"><div className="avatar-lux large"><CircleUserRound/></div><div><div className="eyebrow">Candidate intelligence dossier</div><DialogTitle className="mt-1 font-display text-3xl">{row.full_name}</DialogTitle><DialogDescription className="mt-2 text-white/35">{row.reference_number||row.id} · {row.location||"Location not recorded"}</DialogDescription></div></div><Badge className={tone(stageLabel[row.stage]||row.stage)}>{stageLabel[row.stage]||row.stage}</Badge></div></DialogHeader>
 <div className="mt-7 grid grid-cols-2 gap-3 lg:grid-cols-4">{[["Current flow",f],["Readiness",pct+"%"],["Verification",ok?"Verified":"Not verified"],["Next gate",nextGate(f)]].map(([a,b])=><div className="profile-metric" key={a}><div className="eyebrow">{a}</div><div className="mt-1 truncate text-sm">{b}</div></div>)}</div></div>
 <div className="grid gap-5 p-5 md:p-7 lg:grid-cols-[1.35fr_.65fr]"><div className="space-y-5"><Section icon={BriefcaseBusiness} title="Role & experience" eyebrow="CY review"><div className="grid gap-4 sm:grid-cols-2"><DetailField label="Role / assignment" value={row.program}/><DetailField label="Education" value={row.education}/><DetailField label="Prior experience" value={row.prior_experience}/><DetailField label="Capability / fitness" value={row.fitness_level}/><DetailField label="Source" value={row.source}/><DetailField label="Recruiter" value={recruiter}/></div></Section>
 <Section icon={ShieldCheck} title="Verification evidence" eyebrow="Evidence layer">{records.length?records.map((x,i)=><div key={i} className="evidence-row"><div><div className="text-sm">{x.verification_type||"Verification check"}</div><div className="eyebrow mt-1">{x.provider||"Provider not recorded"}</div></div><Badge className={tone(x.status)}>{x.status}</Badge></div>):<div className="lux-empty small">No verification record returned.</div>}</Section>
 <Section icon={Sparkles} title="Decision context" eyebrow="Next action"><div className="lux-callout">Current stage: <b>{stageLabel[row.stage]||row.stage}</b>. {nextCopy(f)}<div className="mt-4 flex flex-wrap gap-2"><Badge variant="outline" className="border-amber-200/15 text-amber-100/70">{f==="shortlist"?"CY consideration gate":f==="interview"?"Interview / outcome required":f==="selected"?"Terms remain separate":f==="onboarding"?"Readiness confirmation":f==="placed"?"Retention measurement":"Progress only from recorded evidence"}</Badge></div></div></Section></div>
 <aside className="space-y-5"><div className="lux-aside"><div className="eyebrow">CEO glance</div><div className="mt-2 font-display text-xl">Decision readiness</div><div className="mt-4 font-tactical text-5xl text-gradient-gold">{pct}%</div><div className="mt-3 h-2 rounded-full bg-white/7 overflow-hidden"><div className="h-full bg-gradient-to-r from-amber-400 to-yellow-100" style={{width:pct+"%"}}/></div><div className="mt-5 space-y-2">{checks.map(([l,x])=><div key={l as string} className="flex gap-2 text-xs">{x?<CheckCircle2 className="h-3.5 w-3.5 text-emerald-300"/>:<XCircle className="h-3.5 w-3.5 text-white/20"/>}<span className={x?"text-white/60":"text-white/30"}>{l}</span></div>)}</div></div>
 <div className="lux-panel"><div className="eyebrow">Contact</div><div className="mt-4 space-y-3"><DetailField label="Phone" value={row.phone}/><DetailField label="Email" value={row.email}/><DetailField label="Availability / cohort" value={row.cohort}/></div></div>
 <div className="lux-panel"><div className="eyebrow">Governance</div><div className="mt-4 space-y-2"><Governance label="CY decision" value={["accepted","enrolled","certified","deployed"].includes(row.stage)?"Recorded":"Pending"}/><Governance label="Placement" value={row.stage==="deployed"?"Placed":"Not placed"}/><Governance label="Updated" value={new Date(row.updated_at).toLocaleDateString()}/></div></div></aside></div></DialogContent></Dialog>
}
function Section({icon:I,title,eyebrow,children}:any){return <section className="lux-panel"><div className="flex items-center gap-2 text-amber-200/60"><I className="h-4 w-4"/><span className="eyebrow">{eyebrow}</span></div><h3 className="mt-1 font-display text-xl">{title}</h3><div className="mt-5">{children}</div></section>}
function DetailField({label,value}:{label:string;value:string|null}){return <div><div className="eyebrow">{label}</div><div className="mt-1 text-sm leading-6 text-white/65">{value||"Not recorded"}</div></div>}
function Governance({label,value}:{label:string;value:string}){return <div className="flex justify-between rounded-xl border border-white/7 bg-white/[.02] px-3 py-2.5 text-xs"><span className="text-white/35">{label}</span><span className="text-white/65">{value}</span></div>}
function nextGate(f:Flow){return ({all:"Review",applicants:"Screen",screening:"Verify",verification:"Shortlist",shortlist:"Interview",interview:"Select",selected:"Onboard",onboarding:"Place",placed:"Measure"} as Record<Flow,string>)[f]}
function nextCopy(f:Flow){return ({all:"Review the dossier.",applicants:"Complete screening before progression.",screening:"Assess role fit and evidence before verification.",verification:"Review verification evidence before shortlist.",shortlist:"Candidate is at the CY consideration gate.",interview:"CY interview and final decision are required.",selected:"Selection is recorded; engagement terms remain a separate gate.",onboarding:"Confirm onboarding requirements before placement.",placed:"Placement is recorded; continue retention measurement."} as Record<Flow,string>)[f]}
