import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { SEO } from "@/components/SEO";
import { supabase } from "@/integrations/supabase/client";

export default function FarmReports(){
 const [loading,setLoading]=useState(true); const [d,setD]=useState<any>({});
 async function load(){setLoading(true);const [w,g,r,q,p,a,e]=await Promise.all([supabase.from("farm_workers").select("id",{count:"exact",head:true}),supabase.from("farm_workforce_gaps").select("id",{count:"exact",head:true}).eq("status","open"),supabase.from("farm_daily_reports").select("id",{count:"exact",head:true}),supabase.from("farm_requisitions").select("id",{count:"exact",head:true}).eq("status","open"),supabase.from("farm_placements").select("fee_amount"),supabase.from("farm_action_queue").select("id",{count:"exact",head:true}).neq("status","completed"),supabase.from("farm_exceptions").select("id",{count:"exact",head:true}).eq("status","open")]);setD({workers:w.count??0,gaps:g.count??0,reports:r.count??0,requisitions:q.count??0,placements:p.data?.length??0,fees:(p.data??[]).reduce((s:any,x:any)=>s+Number(x.fee_amount??0),0),actions:a.count??0,exceptions:e.count??0});setLoading(false);}
 useEffect(()=>{load();},[]);
 return <div className="min-h-screen bg-[#070707] text-white"><SEO title="Executive Reports • Farm Command Center" noindex/><header className="border-b border-white/10"><div className="container flex min-h-16 items-center justify-between"><Link to="/admin/farm-command-center" className="flex items-center gap-2 text-white/70"><ArrowLeft className="h-4 w-4"/> Command Center</Link><Button variant="glass" size="sm" onClick={load}><RefreshCw className={loading?"h-4 w-4 animate-spin":"h-4 w-4"}/></Button></div></header><main className="container py-8"><div className="text-[10px] uppercase tracking-[.28em] text-amber-300">Executive reporting</div><h1 className="mt-2 font-display text-4xl font-bold">CY Workforce & Operations Brief</h1><p className="mt-2 text-sm text-white/50">Actual recorded data only. Targets are not inferred.</p><div className="mt-8 grid grid-cols-2 lg:grid-cols-4 gap-3">{Object.entries(d).map(([k,v])=><div key={k} className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><div className="text-[10px] uppercase tracking-widest text-white/40">{k.replaceAll("_"," ")}</div><div className="mt-3 text-2xl font-bold">{k==="fees"&&Number(v)>0?"₦"+Number(v).toLocaleString():String(v)}</div></div>)}</div><div className="mt-8 rounded-2xl border border-amber-300/20 bg-amber-300/[.04] p-5 text-sm text-white/60">Classification: <strong className="text-white">recorded actuals</strong>. Missing data and pending verification remain explicit.</div></main></div>;
}